modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/andrew0030/OnlineDetector/issues"
logoFile="logo.png"
license="GNU Lesser General Public License v3.0"

[[mods]]
    modId="online_detector"
    version="1.18.2-2.1.1"
    displayName="Online Detector"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/online-detector"
    credits=""
    authors="andrew0030"
    description='''Online Detector is a Mod that adds Blocks, that allow you to detect if a Player is online.'''

[[dependencies.online_detector]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.online_detector]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"